"""Research journal generation for campaigns."""

from __future__ import annotations

from axiom.grand_challenge.models import Campaign


def generate_campaign_journal(campaign: Campaign) -> str:
    """Assemble a research journal from campaign entries and experiment records."""
    lines = [
        f"# Research Journal: {campaign.name}",
        "",
        f"**Campaign ID:** {campaign.campaign_id}",
        f"**Status:** {campaign.status.value}",
        f"**Current Tier:** {int(campaign.current_tier)}",
        f"**Progress:** {campaign.progress_fraction():.0%}",
        "",
        "## Campaign Description",
        "",
        campaign.description or "_No description provided._",
        "",
        "## Hypotheses",
        "",
    ]

    if campaign.hypotheses:
        for h in campaign.hypotheses:
            lines.append(f"- **{h.statement}** (confidence: {h.confidence:.2f}, status: {h.status})")
    else:
        lines.append("_No hypotheses recorded._")

    lines += ["", "## Experiments", ""]
    if campaign.experiments:
        for e in campaign.experiments:
            status = e.status.value
            score = f", score={e.score:.2f}" if e.score is not None else ""
            passed = f", passed={e.passed}" if e.passed is not None else ""
            lines.append(f"- [{status}] {e.title} (challenge: {e.challenge_id}{score}{passed})")
            if e.notes:
                lines.append(f"  - {e.notes}")
    else:
        lines.append("_No experiments recorded._")

    lines += ["", "## Evidence Trail", ""]
    if campaign.evidence:
        for ev in campaign.evidence:
            lines.append(f"- [{ev.evidence_tier.value}] {ev.source}: {ev.content[:120]}")
    else:
        lines.append("_No evidence collected._")

    lines += ["", "## Journal Entries", ""]
    if campaign.journal:
        for entry in campaign.journal:
            lines += [f"### {entry.title} ({entry.phase})", "", entry.content, ""]
    else:
        lines.append("_No journal entries._")

    lines += [
        "## Checkpoints",
        "",
    ]
    if campaign.checkpoints:
        for cp in campaign.checkpoints:
            lines.append(
                f"- Tier {int(cp.tier)}: {len(cp.challenges_completed)} challenges, "
                f"{cp.experiments_completed} experiments, {cp.evidence_count} evidence records "
                f"({cp.created_at.isoformat()})"
            )
    else:
        lines.append("_No checkpoints saved._")

    lines += ["", "---", "*Generated by AXIOM Grand Challenge Program*"]
    return "\n".join(lines)
