"""Add embeddings and indexing_status

Revision ID: 5d86255fc7dc
Revises: 2e7e166ffe7e
Create Date: 2026-08-12 17:05:58.309723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d86255fc7dc'
down_revision: Union[str, Sequence[str], None] = '2e7e166ffe7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('indexing_status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'indexing_status')
    # ### end Alembic commands ###
