"""Add embeddings and indexing_status

Revision ID: 647aeab7ab1e
Revises: 5d86255fc7dc
Create Date: 2026-08-12 17:06:02.360533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647aeab7ab1e'
down_revision: Union[str, Sequence[str], None] = '5d86255fc7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
