"""add_chunk_metadata_columns

Revision ID: c2e46185a739
Revises: 7a8f901b2c3d
Create Date: 2026-08-21 18:29:50.756781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e46185a739'
down_revision: Union[str, Sequence[str], None] = '7a8f901b2c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add chunk metadata columns — use server_default to satisfy SQLite NOT NULL restriction
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('document_chunks', sa.Column('char_start', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('char_end', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_dim', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_dim')
    op.drop_column('document_chunks', 'char_end')
    op.drop_column('document_chunks', 'char_start')
    op.drop_column('document_chunks', 'chunk_index')
    op.create_table('equivalent_statements',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('statement_a_id', sa.TEXT(), nullable=False),
    sa.Column('statement_b_id', sa.TEXT(), nullable=False),
    sa.Column('equivalence_type', sa.TEXT(), server_default=sa.text("'IFF'"), nullable=True),
    sa.Column('proof_reference', sa.TEXT(), nullable=True),
    sa.Column('confidence', sa.REAL(), server_default=sa.text('(1.0)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_schema_migrations',
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('applied_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.create_table('mathematical_objects',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('node_id', sa.TEXT(), nullable=False),
    sa.Column('object_type', sa.TEXT(), nullable=False),
    sa.Column('formal_symbol', sa.TEXT(), nullable=True),
    sa.Column('domain', sa.TEXT(), nullable=True),
    sa.Column('properties_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.TEXT(), nullable=False),
    sa.Column('snapshot', sa.TEXT(), nullable=False),
    sa.Column('domain', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failed_proof_attempts',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('claim_id', sa.TEXT(), nullable=False),
    sa.Column('tactic_sequence', sa.TEXT(), nullable=True),
    sa.Column('verifier', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('definitions',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('node_id', sa.TEXT(), nullable=False),
    sa.Column('term', sa.TEXT(), nullable=False),
    sa.Column('formal_definition', sa.TEXT(), nullable=True),
    sa.Column('informal_definition', sa.TEXT(), nullable=True),
    sa.Column('domain', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof_lineage',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('claim_id', sa.TEXT(), nullable=False),
    sa.Column('parent_claim_id', sa.TEXT(), nullable=True),
    sa.Column('proof_strategy', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'PENDING'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('source_id', sa.TEXT(), nullable=False),
    sa.Column('target_id', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('confidence', sa.REAL(), server_default=sa.text('(1.0)'), nullable=True),
    sa.Column('provenance', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id', 'type')
    )
    # ### end Alembic commands ###
