"""Research Reporter — produces final evidence-backed report."""

from __future__ import annotations

from typing import TYPE_CHECKING

from axiom.research_loop.schema import ClaimStatus, ResearchPhase

if TYPE_CHECKING:
    from axiom.research_loop.workers.context import ResearchLoopContext


class ResearchReporterWorker:
    worker_type = "research_reporter"
    mission = "Generate final report with claim statuses and provenance"

    async def execute(self, ctx: "ResearchLoopContext") -> dict:
        state = ctx.state
        state.current_phase = ResearchPhase.REPORT
        state.active_workers = [self.worker_type]

        lines = [
            f"# Research Report",
            "",
            f"**Question:** {state.research_question}",
            f"**Iterations:** {state.current_iteration}/{state.max_iterations}",
            f"**Confidence:** {state.confidence:.2f}",
            "",
            "## Subproblems",
            *[f"- {s}" for s in state.subproblems],
            "",
            "## Evidence",
        ]
        for e in state.evidence[:10]:
            lines.append(f"- [{e.claim_status.value}] ({e.source}): {e.content[:120]}")

        lines.extend(["", "## Hypotheses"])
        for h in sorted(state.hypotheses, key=lambda x: x.rank):
            status = "REJECTED" if h.rejected else h.status.value
            lines.append(f"- [{status}] (score={h.score:.2f}) {h.statement}")

        lines.extend(["", "## Verified Claims"])
        for c in state.claims:
            lines.append(f"- [{c.status.value}] {c.statement}")

        lines.extend(["", "## Experiments"])
        for ex in state.experiments:
            lines.append(f"- {'✓' if ex.success else '✗'} {ex.description}: {ex.result}")

        if state.failed_attempts:
            lines.extend(["", "## Failed Approaches (Failure Memory)"])
            for f in state.failed_attempts:
                lines.append(f"- **{f.approach[:80]}** — {f.failure_reason}")
                if f.learned:
                    lines.append(f"  - Learned: {f.learned}")

        lines.extend(["", "## Conclusion"])
        top_claims = [c for c in state.claims if c.status in (ClaimStatus.SUPPORTED, ClaimStatus.KNOWN)]
        if top_claims:
            lines.append("Based on verified evidence:")
            for c in top_claims[:3]:
                lines.append(f"- [{c.status.value}] {c.statement}")
        else:
            lines.append("No claims reached SUPPORTED status. Further iteration required.")

        lines.extend([
            "",
            "## Provenance",
            f"- Sources consulted: {len(state.sources)}",
            f"- Human interventions: {state.human_interventions}",
            f"- Timeline events: {len(state.timeline)}",
            "",
            "*This report was generated by AXIOM Autonomous Research Loop v1. "
            "Model-generated statements are classified, not treated as discoveries.*",
        ])

        report = "\n".join(lines)
        state.final_report = report
        state.current_phase = ResearchPhase.COMPLETED
        state.add_timeline(ResearchPhase.REPORT, "Final report generated", self.worker_type)
        state.active_workers = []
        return {"report_length": len(report)}
