"""Generate RVP markdown reports."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from axiom.research_validation.dashboard import build_dashboard
from axiom.research_validation.dataset import dataset_stats
from axiom.research_validation.engine import ResearchValidationEngine
from axiom.research_validation.models import STAGE_DESCRIPTIONS, ValidationStage
from axiom.research_validation.store import RVPStore


def generate_research_validation_md(dashboard: dict[str, Any], stats: dict[str, int]) -> str:
    lines = [
        "# Research Validation Program",
        "",
        "**Mission:** Scientifically validate that AXIOM improves research — without claiming discovery.",
        "",
        "## Staged Validation Framework",
        "",
        "| Stage | Name | Description | Problems |",
        "|------:|------|-------------|----------:|",
    ]
    for stage in ValidationStage:
        count = stats.get(f"stage_{int(stage)}", 0)
        lines.append(f"| {int(stage)} | {stage.name} | {STAGE_DESCRIPTIONS[stage]} | {count} |")

    lines += [
        "",
        "## Program Status",
        "",
        f"- **Dataset size:** {stats.get('total', 0)} known-answer problems (answers hidden during execution)",
        f"- **Completed experiments:** {dashboard.get('completed_experiments', 0)}",
        f"- **Success rate:** {dashboard.get('success_rate', 0):.1%}",
        f"- **Average latency:** {dashboard.get('latency_ms_avg', 0):.1f} ms",
        "",
        "## Research Capability Score Dimensions",
        "",
        "Every run produces scores for: Problem Understanding, Planning, Literature Retrieval,",
        "Knowledge Integration, Reasoning, Evidence Quality, Verification, Recovery From Failure,",
        "Reproducibility, and Human Intervention Required.",
        "",
        "## Discovery Pipeline Outputs",
        "",
        "Each completed run produces: Research Report, Reasoning Tree, Evidence Graph,",
        "Hypothesis List, Rejected Hypotheses, Failed Attempts, Lessons Learned,",
        "Confidence Estimates, and Future Work.",
        "",
        "## Honesty Contract",
        "",
        "> AXIOM does **not** claim scientific discovery. We prove measurable improvement",
        "> on benchmarked research tasks with stated limitations and hidden-answer validation.",
        "",
        "---",
        "*Generated by AXIOM Research Validation Program.*",
    ]
    return "\n".join(lines)


def generate_benchmark_results_md(dashboard: dict[str, Any]) -> str:
    trends = dashboard.get("benchmark_trends", {})
    lines = [
        "# Benchmark Results",
        "",
        "## Success Rate",
        "",
        f"**Overall:** {dashboard.get('success_rate', 0):.1%} ({dashboard.get('completed_experiments', 0)} runs)",
        "",
        "## Answer Scores by Stage",
        "",
        "| Stage | Mean Answer Score |",
        "|------:|------------------:|",
    ]
    for stage, score in sorted(trends.items(), key=lambda x: int(x[0])):
        lines.append(f"| {stage} | {score:.3f} |")

    lines += [
        "",
        "## Failure Reasons",
        "",
    ]
    failures = dashboard.get("failure_reasons", {})
    if failures:
        for reason, count in failures.items():
            lines.append(f"- **{reason}:** {count}")
    else:
        lines.append("- No failures recorded yet.")

    lines += [
        "",
        "## Cost & Latency",
        "",
        f"- Total cost (proxy ms): {dashboard.get('cost_ms_total', 0):.1f}",
        f"- Average latency: {dashboard.get('latency_ms_avg', 0):.1f} ms",
        "",
        "---",
        "*Run `python3 scripts/run_research_validation.py` to refresh.*",
    ]
    return "\n".join(lines)


def generate_capability_score_md(dashboard: dict[str, Any]) -> str:
    trends = dashboard.get("capability_trends", {})
    lines = [
        "# Research Capability Score",
        "",
        "Unified 10-dimension score (0.0–1.0 per dimension). Composite averages all dimensions;",
        "Human Intervention Required is inverted (lower intervention = higher contribution).",
        "",
        "## Current Aggregate Scores",
        "",
        "| Dimension | Score |",
        "|-----------|------:|",
    ]
    for dim, score in sorted(trends.items()):
        label = dim.replace("_", " ").title()
        lines.append(f"| {label} | {score:.3f} |")

    if trends:
        composite_dims = list(trends.values())
        composite = sum(composite_dims) / len(composite_dims)
        lines.append(f"| **Composite (approx)** | **{composite:.3f}** |")

    lines += [
        "",
        "## Interpretation",
        "",
        "- Scores below 0.5 indicate heuristic baseline; LLM-backed runs expected to improve reasoning and literature retrieval.",
        "- Verification and evidence quality depend on formal tooling integration (S0-E3/S0-E4).",
        "",
        "---",
        "*Per-run scores stored in `rvp_runs` SQLite table.*",
    ]
    return "\n".join(lines)


def generate_next_targets_md(dashboard: dict[str, Any]) -> str:
    lines = [
        "# Next Research Targets",
        "",
        "## ONE Recommended Initiative",
        "",
        "### H1-OBS — Evaluation Provenance Records",
        "",
        "Attach reproducible provenance (inputs, runtime, configuration, evidence tier) to every",
        "RVP and SCEP evaluation run. S0-E4 evidence gate is complete; provenance is the highest-leverage",
        "next step to make validation results independently auditable and replayable at scale.",
        "",
        "## Staged Progression",
        "",
        "| Priority | Target | Rationale |",
        "|---------:|--------|-----------|",
        "| 1 | Complete Stage 0 infrastructure runs | Establish replay and dashboard baseline |",
        "| 2 | Stage 1 known-answer batch (n≥50) | Measure answer-score trend before claiming improvement |",
        "| 3 | Wire LLM to research reports | Replace heuristic templates with model-backed reasoning |",
        "| 4 | Stage 2 paper reproduction pilots | Test on 5 canonical ML/math papers |",
        "| 5 | Per-user research isolation | Required before external validation participants |",
        "",
        "## Weak Dimensions (from latest runs)",
        "",
    ]
    trends = dashboard.get("capability_trends", {})
    if trends:
        weakest = sorted(trends.items(), key=lambda x: x[1])[:3]
        for dim, score in weakest:
            lines.append(f"- **{dim.replace('_', ' ')}** — {score:.3f}")
    else:
        lines.append("- Run validation batch first to identify weak dimensions.")

    lines += [
        "",
        "---",
        "*Exactly one initiative recommended per cycle. See `.axiom/TASK_QUEUE.md`.*",
    ]
    return "\n".join(lines)


def write_all_reports(workspace: Path, db_path: str) -> dict[str, Path]:
    """Generate and write all four RVP markdown reports."""
    store = RVPStore(db_path)
    dashboard = build_dashboard(store)
    stats = dataset_stats()

    reports = {
        "RESEARCH_VALIDATION.md": generate_research_validation_md(dashboard, stats),
        "BENCHMARK_RESULTS.md": generate_benchmark_results_md(dashboard),
        "CAPABILITY_SCORE.md": generate_capability_score_md(dashboard),
        "NEXT_RESEARCH_TARGETS.md": generate_next_targets_md(dashboard),
    }
    written: dict[str, Path] = {}
    for name, content in reports.items():
        path = workspace / name
        path.write_text(content, encoding="utf-8")
        written[name] = path
    return written
