"""Research report generation."""

from __future__ import annotations

from axiom.research_kernel.models import KernelRun, KernelStage, STAGE_ORDER
from axiom.research_kernel.plugin import ResearchDomainPlugin


def generate_kernel_report(run: KernelRun, plugin: ResearchDomainPlugin) -> str:
    """Assemble the final research report from kernel run artifacts."""
    domain_section = plugin.generate_domain_report(run.context)
    completed_set = set(run.stages_completed)
    if run.current_stage == KernelStage.REPORT_GENERATION or run.report is not None:
        completed_set.add(KernelStage.REPORT_GENERATION)
    stages_summary = "\n".join(
        f"- **{s.value}**: {'✓' if s in completed_set else '✗'}"
        for s in STAGE_ORDER
    )
    benchmarks = run.benchmark_results
    passed = sum(1 for b in benchmarks if b.get("passed"))
    verify = run.context.get("verification", {})

    return (
        f"# AXIOM Research Kernel Report\n\n"
        f"**Run ID:** {run.run_id}\n"
        f"**Domain:** {run.domain} ({plugin.name})\n"
        f"**Objective:** {run.objective}\n"
        f"**Status:** {run.status.value}\n\n"
        f"## Pipeline Stages\n\n{stages_summary}\n\n"
        f"## Verification Summary\n\n"
        f"- Verified claims: {verify.get('verified_claims', 0)}\n"
        f"- Passed: {verify.get('passed', False)}\n\n"
        f"## Benchmark Results\n\n"
        f"**{passed}/{len(benchmarks)}** benchmarks passed\n\n"
        f"{domain_section}\n\n"
        f"---\n*Generated by AXIOM Research Kernel v1.0.0*\n"
    )
