"""Markdown report generators for engineering governance."""

from __future__ import annotations

from axiom.governance.models import GovernanceSnapshot, Severity


def generate_engineering_health(snapshot: GovernanceSnapshot) -> str:
    scores = snapshot.scores
    lines = [
        "# Engineering Health Report",
        "",
        f"**Generated:** {snapshot.timestamp}",
        f"**Workspace:** `{snapshot.workspace_root}`",
        "",
        "## Cycle Scores",
        "",
        "| Score | Value | Interpretation |",
        "|-------|------:|----------------|",
        f"| Engineering Health | **{scores.engineering_health:.0f}** | Code, architecture, testing discipline |",
        f"| Product Health | **{scores.product_health:.0f}** | MVP wedge readiness and UX honesty |",
        f"| Research Capability | **{scores.research_capability:.0f}** | Scientific benchmarks and AI depth |",
        f"| Technical Debt | **{scores.technical_debt:.0f}** | Higher = more debt (inverse health) |",
        f"| Security | **{scores.security:.0f}** | Auth, tenancy, dependency risk |",
        f"| Performance | **{scores.performance:.0f}** | Import time and benchmark regressions |",
        f"| Developer Experience | **{scores.developer_experience:.0f}** | Docs, CI, onboarding |",
        f"| Repository Maturity | **{scores.repository_maturity:.0f}** | Composite engineering maturity |",
        "",
        "## Governance Systems Active",
        "",
        "| System | Status | Collector |",
        "|--------|--------|-----------|",
    ]
    systems = [
        ("Technical debt tracking", "technical_debt"),
        ("Dependency health monitoring", "dependencies"),
        ("Code quality scoring", "code_quality"),
        ("Architecture consistency checking", "architecture"),
        ("Performance regression detection", "performance"),
        ("Security scanning", "security"),
        ("Documentation coverage", "documentation"),
        ("Test coverage reporting", "testing"),
        ("Benchmark regression reporting", "benchmarks"),
        ("Repository health dashboard", "dashboard"),
    ]
    for label, key in systems:
        status = "✅" if key in snapshot.collectors or key == "dashboard" else "❌"
        lines.append(f"| {label} | {status} | `{key}` |")

    lines += [
        "",
        "## Engineering Council Recommendations",
        "",
    ]
    for rec in snapshot.council:
        lines += [
            f"### {rec.role}",
            f"*{rec.domain}*",
            "",
            f"**Recommendation:** {rec.recommendation}",
            "",
            f"**Rationale:** {rec.rationale}",
            "",
        ]

    lines += [
        "## Highest-Leverage Initiative (ONE)",
        "",
        f"### {snapshot.top_initiative}",
        "",
        snapshot.top_initiative_rationale,
        "",
        "---",
        "*Generated by AXIOM Engineering Governance System. Re-run: `make engineering-health`*",
    ]
    return "\n".join(lines)


def generate_product_health(snapshot: GovernanceSnapshot) -> str:
    scores = snapshot.scores
    product_findings = [f for f in snapshot.all_findings if f.category.value in ("debt", "documentation", "testing")]
    lines = [
        "# Product Health Report",
        "",
        f"**Generated:** {snapshot.timestamp}",
        f"**Product Health Score:** **{scores.product_health:.0f}/100**",
        "",
        "## What is broken?",
        "",
    ]
    broken = [f for f in product_findings if f.severity in (Severity.CRITICAL, Severity.HIGH)]
    for f in broken[:10]:
        lines.append(f"- **{f.title}** — {f.recommendation}")
    if not broken:
        lines.append("- No critical/high product findings in this cycle.")

    lines += [
        "",
        "## What should be tested?",
        "",
        "- Per-user data isolation (auth + research store scoping)",
        "- Register/login/register spam and brute-force resistance",
        "- PDF upload edge cases (scanned PDFs, large files)",
        "- Research Q&A with configured vs mock model gateway",
        "",
        "## What should be documented?",
        "",
        "- MVP_READINESS.md blockers kept current after each release",
        "- Demo vs Research mode contracts (`docs/MODES.md` when available)",
        "- API authentication flows in `docs/api.md`",
        "",
        "## Product Engineering Council View",
        "",
    ]
    for rec in snapshot.council:
        if rec.role == "Product Engineering Lead":
            lines += [f"**{rec.recommendation}**", "", rec.rationale, ""]

    lines += [
        "---",
        "*Product health reflects Research Workspace wedge readiness, not full platform vision.*",
    ]
    return "\n".join(lines)


def generate_research_health(snapshot: GovernanceSnapshot) -> str:
    scores = snapshot.scores
    bench = snapshot.collectors.get("benchmarks")
    lines = [
        "# Research Health Report",
        "",
        f"**Generated:** {snapshot.timestamp}",
        f"**Research Capability Score:** **{scores.research_capability:.0f}/100**",
        "",
        "## Benchmark Status",
        "",
    ]
    if bench:
        for m in bench.metrics:
            lines.append(f"- **{m.name}:** {m.value}{m.unit}")
        regressions = [f for f in bench.findings if "regression" in f.title.lower()]
        if regressions:
            lines += ["", "### Regressions", ""]
            for f in regressions:
                lines.append(f"- {f.title}: {f.detail}")
    else:
        lines.append("- No benchmark collector data.")

    lines += [
        "",
        "## What should be benchmarked?",
        "",
        "- EPIC-002 capability dimensions (mathematical reasoning, proof verification, etc.)",
        "- Research loop worker output quality when LLM is wired",
        "- Prize readiness composite scores over time",
        "- Eval API evidence tier accuracy after S0-E4",
        "",
        "## What should be optimized next?",
        "",
        "- Wire ModelClient to research loop workers (heuristic → model-backed)",
        "- Complete S0-E4 evidence gate before expanding eval surface",
        "- Add semantic search benchmark once embeddings exist",
        "",
        "## AI Systems Council View",
        "",
    ]
    for rec in snapshot.council:
        if rec.role == "AI Systems Lead":
            lines += [f"**{rec.recommendation}**", "", rec.rationale, ""]

    lines += [
        "---",
        "*Research health measures scientific capability evidence, not demo polish.*",
    ]
    return "\n".join(lines)


def generate_tech_debt_board(snapshot: GovernanceSnapshot) -> str:
    debt_findings = [f for f in snapshot.all_findings if f.category.value == "debt"]
    lines = [
        "# Technical Debt Board",
        "",
        f"**Generated:** {snapshot.timestamp}",
        f"**Technical Debt Score:** **{snapshot.scores.technical_debt:.0f}/100** (higher = more debt)",
        "",
        "## Active Debt Items",
        "",
        "| Severity | Item | Source | Recommendation |",
        "|----------|------|--------|----------------|",
    ]
    for f in debt_findings:
        lines.append(f"| {f.severity.value} | {f.title} | {f.source} | {f.recommendation} |")

    lines += [
        "",
        "## What should be refactored?",
        "",
        "- Research store: add user_id column and query scoping",
        "- Eval API: replace hardcoded `/eval/scores` fallback with evidence-gated responses",
        "- MDE router: consolidate stub routes vs production mounting",
        "",
        "## What should be deleted?",
        "",
        "- Stale capability delta reports (`docs/capability_delta_*.md`) — do not bulk-commit",
        "- Unused graph workspace code paths if not on roadmap",
        "- Duplicate ruff/mypy config if consolidated in pyproject.toml",
        "",
        "## What is duplicated?",
        "",
        "- Two UI surfaces: `/workspace` graph vs `/research` workspace (no shared context)",
        "- Eval framework vs hardcoded score endpoints",
        "- Demo scripts overlapping MVP and research workspace flows",
        "",
        "---",
        "*Debt board is regenerated each engineering cycle from repo evidence.*",
    ]
    return "\n".join(lines)


def generate_top_25_priorities(snapshot: GovernanceSnapshot) -> str:
    lines = [
        "# Top 25 Engineering Priorities",
        "",
        f"**Generated:** {snapshot.timestamp}",
        "",
        "## Ranked Priorities",
        "",
        "| Rank | Priority | Action |",
        "|-----:|----------|--------|",
    ]
    for rank, title, action in snapshot.priorities:
        lines.append(f"| {rank} | {title} | {action} |")

    lines += [
        "",
        "## ONE Initiative — Highest Long-Term Leverage",
        "",
        f"### {snapshot.top_initiative}",
        "",
        snapshot.top_initiative_rationale,
        "",
        "> **Note:** Only ONE initiative is recommended per engineering cycle. "
        "All other priorities support or follow this gate.",
        "",
        "---",
        "*Priorities ranked by severity, score impact, and council review.*",
    ]
    return "\n".join(lines)


def generate_dashboard_json(snapshot: GovernanceSnapshot) -> str:
    import json

    payload = {
        "timestamp": snapshot.timestamp,
        "scores": snapshot.scores.as_dict(),
        "collectors": {
            name: {
                "metrics": [
                    {"name": m.name, "value": m.value, "unit": m.unit, "status": m.status}
                    for m in result.metrics
                ],
                "finding_count": len(result.findings),
            }
            for name, result in snapshot.collectors.items()
        },
        "finding_summary": {
            sev.value: sum(1 for f in snapshot.all_findings if f.severity == sev)
            for sev in Severity
        },
        "top_initiative": snapshot.top_initiative,
    }
    return json.dumps(payload, indent=2) + "\n"
