"""
Prometheus Metrics — AXIOM Observability Layer
===============================================
Exposes counters and histograms for all AXIOM subsystems.
The FastAPI gateway mounts a `/metrics` endpoint that serves
the Prometheus text format.

Usage:
    from axiom.observability.metrics import METRICS
    METRICS.hypotheses_generated.inc()
    with METRICS.proof_search_duration.time():
        result = mcts.solve(...)
"""

from __future__ import annotations

import time
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Dict


# ── Minimal Prometheus-compatible metrics (no external deps required) ─────────
# In production, swap this with `prometheus_client` for full Prometheus support.

class _Counter:
    """A monotonically increasing counter."""
    def __init__(self, name: str, description: str, labels: list[str] | None = None):
        self.name = name
        self.description = description
        self._values: Dict[tuple, float] = defaultdict(float)
        self._labels = labels or []

    def inc(self, amount: float = 1.0, **label_values: str) -> None:
        key = tuple(label_values.get(l, "") for l in self._labels)
        self._values[key] += amount

    def collect(self) -> list[tuple[dict, float]]:
        return [(dict(zip(self._labels, k)), v) for k, v in self._values.items()]


class _Histogram:
    """A cumulative histogram with configurable buckets."""
    BUCKETS = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]

    def __init__(self, name: str, description: str):
        self.name = name
        self.description = description
        self._sum = 0.0
        self._count = 0
        self._buckets: Dict[float, int] = {b: 0 for b in self.BUCKETS}

    def observe(self, value: float) -> None:
        self._sum += value
        self._count += 1
        for b in self.BUCKETS:
            if value <= b:
                self._buckets[b] += 1

    def time(self) -> "_Timer":
        return _Timer(self)

    def collect(self) -> dict:
        return {
            "sum": self._sum,
            "count": self._count,
            "buckets": {str(b): v for b, v in self._buckets.items()},
        }


class _Timer:
    def __init__(self, histogram: _Histogram):
        self._h = histogram
        self._start: float = 0.0

    def __enter__(self) -> "_Timer":
        self._start = time.monotonic()
        return self

    def __exit__(self, *_: object) -> None:
        self._h.observe(time.monotonic() - self._start)


@dataclass
class AxiomMetrics:
    """Central metrics registry for all AXIOM subsystems."""

    # ── Ingestion ─────────────────────────────────────────────────────────────
    papers_ingested: _Counter = field(default_factory=lambda: _Counter(
        "axiom_papers_ingested_total",
        "Total papers ingested from arXiv",
    ))
    claims_extracted: _Counter = field(default_factory=lambda: _Counter(
        "axiom_claims_extracted_total",
        "Mathematical claims extracted from papers",
    ))

    # ── Knowledge Graph ───────────────────────────────────────────────────────
    graph_nodes_total: _Counter = field(default_factory=lambda: _Counter(
        "axiom_graph_nodes_total",
        "Total nodes added to the epistemic graph store",
        labels=["node_type"],
    ))
    graph_edges_total: _Counter = field(default_factory=lambda: _Counter(
        "axiom_graph_edges_total",
        "Total edges added to the epistemic graph store",
    ))

    # ── Verification ─────────────────────────────────────────────────────────
    smt_checks_total: _Counter = field(default_factory=lambda: _Counter(
        "axiom_smt_checks_total",
        "Total SMT verification checks run",
        labels=["result"],  # "valid" | "refuted" | "unknown"
    ))
    lean_exports_total: _Counter = field(default_factory=lambda: _Counter(
        "axiom_lean_exports_total",
        "Total Lean 4 theorem files exported",
    ))
    proof_search_duration: _Histogram = field(default_factory=lambda: _Histogram(
        "axiom_proof_search_duration_seconds",
        "Duration of MCTS proof search runs",
    ))

    # ── Hypothesis Engine ─────────────────────────────────────────────────────
    hypotheses_generated: _Counter = field(default_factory=lambda: _Counter(
        "axiom_hypotheses_generated_total",
        "Total conjectures generated by the Hypothesis Engine",
        labels=["strategy"],
    ))

    # ── Self-Improvement ──────────────────────────────────────────────────────
    self_improvement_runs: _Counter = field(default_factory=lambda: _Counter(
        "axiom_self_improvement_runs_total",
        "Total self-improvement audit runs",
    ))

    # ── API ───────────────────────────────────────────────────────────────────
    api_requests_total: _Counter = field(default_factory=lambda: _Counter(
        "axiom_api_requests_total",
        "Total API requests processed",
        labels=["method", "endpoint", "status"],
    ))
    api_request_duration: _Histogram = field(default_factory=lambda: _Histogram(
        "axiom_api_request_duration_seconds",
        "API request latency in seconds",
    ))

    def prometheus_text(self) -> str:
        """Render all metrics in Prometheus text exposition format."""
        lines: list[str] = []

        def _render_counter(c: _Counter) -> None:
            lines.append(f"# HELP {c.name} {c.description}")
            lines.append(f"# TYPE {c.name} counter")
            for labels, value in c.collect():
                label_str = ",".join(f'{k}="{v}"' for k, v in labels.items())
                suffix = f"{{{label_str}}}" if label_str else ""
                lines.append(f"{c.name}{suffix} {value}")

        def _render_histogram(h: _Histogram) -> None:
            lines.append(f"# HELP {h.name} {h.description}")
            lines.append(f"# TYPE {h.name} histogram")
            data = h.collect()
            for b, count in data["buckets"].items():
                lines.append(f'{h.name}_bucket{{le="{b}"}} {count}')
            lines.append(f'{h.name}_bucket{{le="+Inf"}} {data["count"]}')
            lines.append(f"{h.name}_sum {data['sum']}")
            lines.append(f"{h.name}_count {data['count']}")

        for attr_name in self.__dataclass_fields__:
            obj = getattr(self, attr_name)
            if isinstance(obj, _Counter):
                _render_counter(obj)
            elif isinstance(obj, _Histogram):
                _render_histogram(obj)

        return "\n".join(lines) + "\n"


# Global singleton
METRICS = AxiomMetrics()
