"""
Department B — Formal Mathematics
Coq proof script generator with fallback simulation.
"""
from __future__ import annotations

import subprocess
import logging
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class CoqResult:
    theorem_name: str
    script: str
    compiled_successfully: Optional[bool] = None
    error_output: str = ""
    fallback_mode: bool = False


def generate_theorem(
    theorem_name: str,
    statement: str,
    namespace: str = "AXIOM",
    hypotheses: list[str] | None = None,
) -> CoqResult:
    """Generate a Coq theorem declaration."""
    hyps_str = ""
    if hypotheses:
        hyps_str = "\n".join(f"  Hypothesis H{i} : {h}." for i, h in enumerate(hypotheses))

    script = f"""(* Auto-generated by AXIOM MIP — Department B (Formal Mathematics) *)
(* Theorem: {theorem_name} *)

Require Import ZArith.
Require Import Reals.
Require Import Lia.
Require Import Ring.

Module {namespace}.

{hyps_str}

Theorem {theorem_name.replace(' ', '_').replace('-', '_')} :
  {statement}.
Proof.
  (* Primary tactics: ring, lia, auto *)
  try ring.
  try lia.
  try auto.
  try omega.
Qed.

End {namespace}.
"""
    return CoqResult(theorem_name=theorem_name, script=script)


def check_coq_available() -> bool:
    try:
        result = subprocess.run(["coqc", "--version"], capture_output=True, timeout=5)
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def compile_coq(script: str, timeout_seconds: int = 30) -> tuple[bool, str]:
    """Compile a Coq script. Falls back to simulation if coqc not available."""
    if not check_coq_available():
        logger.warning("coqc not found — running fallback simulation")
        return _simulate_coq_check(script)

    try:
        import tempfile, os
        with tempfile.NamedTemporaryFile(mode="w", suffix=".v", delete=False) as f:
            f.write(script)
            tmp_path = f.name

        result = subprocess.run(
            ["coqc", tmp_path],
            capture_output=True, text=True, timeout=timeout_seconds,
        )
        os.unlink(tmp_path)
        return result.returncode == 0, result.stderr or result.stdout
    except subprocess.TimeoutExpired:
        return False, "TIMEOUT: Coq compilation exceeded time limit"
    except Exception as exc:
        return False, f"ERROR: {exc}"


def _simulate_coq_check(script: str) -> tuple[bool, str]:
    issues = []
    if "Theorem" not in script and "Lemma" not in script:
        issues.append("No Theorem or Lemma declaration found")
    if "Qed." not in script and "Defined." not in script:
        issues.append("No Qed. or Defined. found (proof not closed)")
    if issues:
        return False, "SIMULATION ERRORS:\n" + "\n".join(issues)
    logger.warning("coqc not installed. Simulation: script appears structurally valid.")
    return True, "SIMULATION: Coq script appears structurally valid (coqc not installed)"
