"""
Department B — Formal Mathematics
Lean 4 theorem and proof script generator.
Integrates with Mathlib 4 tactic library.
"""
from __future__ import annotations

import subprocess
import logging
import re
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)


# Mathlib 4 tactic index — 20 commonly used tactics with applicability predicates
MATHLIB_TACTICS: list[dict] = [
    {"tactic": "ring", "description": "Proves ring/field equalities", "keywords": ["=", "+", "*", "^", "commut", "distribut", "polynomial"]},
    {"tactic": "ring_nf", "description": "Normalizes ring expressions", "keywords": ["simplify", "normalize", "ring", "polynomial"]},
    {"tactic": "norm_num", "description": "Proves numeric equalities/inequalities", "keywords": ["=", "<", ">", "≤", "≥", "numeric", "number", "integer", "rational"]},
    {"tactic": "linarith", "description": "Linear arithmetic over ordered fields", "keywords": ["linear", "≤", "≥", "<", ">", "inequality", "bound"]},
    {"tactic": "nlinarith", "description": "Nonlinear arithmetic", "keywords": ["nonlinear", "product", "square", "≤", "≥", "bound", "x^2"]},
    {"tactic": "omega", "description": "Integer/natural number linear arithmetic", "keywords": ["integer", "natural", "modular", "divisibility", "ℤ", "ℕ"]},
    {"tactic": "simp", "description": "Simplification via rewrite rules", "keywords": ["simplify", "rewrite", "reduce", "trivial"]},
    {"tactic": "exact", "description": "Provide exact proof term", "keywords": ["exact", "trivially", "by definition"]},
    {"tactic": "apply", "description": "Apply a lemma/theorem", "keywords": ["apply", "use", "follows from"]},
    {"tactic": "intro", "description": "Introduce hypotheses/variables", "keywords": ["for all", "∀", "assume", "let"]},
    {"tactic": "constructor", "description": "Prove conjunction or existence", "keywords": ["and", "∧", "exists", "∃", "pair"]},
    {"tactic": "cases", "description": "Case analysis", "keywords": ["cases", "either", "or", "∨", "induction"]},
    {"tactic": "induction", "description": "Mathematical induction", "keywords": ["induction", "base case", "inductive step", "ℕ", "natural"]},
    {"tactic": "contrapose", "description": "Proof by contrapositive", "keywords": ["contrapositive", "contradict", "not", "¬", "if not"]},
    {"tactic": "push_neg", "description": "Push negations inward", "keywords": ["not", "¬", "negation", "∀", "∃"]},
    {"tactic": "field_simp", "description": "Simplify field expressions", "keywords": ["fraction", "division", "denominator", "field", "/"]},
    {"tactic": "positivity", "description": "Prove positivity/non-negativity", "keywords": ["positive", "nonnegative", "> 0", "≥ 0", "abs"]},
    {"tactic": "gcongr", "description": "Generalized congruence for inequalities", "keywords": ["congruence", "monotone", "increasing", "preserv"]},
    {"tactic": "funext", "description": "Function extensionality", "keywords": ["function", "extensional", "equal functions", "∀ x, f x = g x"]},
    {"tactic": "decide", "description": "Decide decidable propositions", "keywords": ["decidable", "finite", "computable", "Bool"]},
]


def suggest_tactics(statement: str) -> list[str]:
    """Suggest Mathlib tactics for a given theorem statement."""
    statement_lower = statement.lower()
    scores: dict[str, int] = {}
    for entry in MATHLIB_TACTICS:
        score = sum(1 for kw in entry["keywords"] if kw.lower() in statement_lower)
        if score > 0:
            scores[entry["tactic"]] = score
    ranked = sorted(scores, key=lambda t: scores[t], reverse=True)
    return ranked[:5] if ranked else ["simp", "ring", "norm_num"]


@dataclass
class Lean4Result:
    theorem_name: str
    script: str
    suggested_tactics: list[str] = field(default_factory=list)
    compiler_available: bool = False
    compiled_successfully: Optional[bool] = None
    error_output: str = ""
    fallback_mode: bool = False


def generate_theorem(
    theorem_name: str,
    statement: str,
    namespace: str = "AXIOM",
    hypotheses: list[str] | None = None,
    variables: list[str] | None = None,
) -> Lean4Result:
    """Generate a Lean 4 theorem declaration with suggested tactics."""
    tactics = suggest_tactics(statement)
    hyps_str = ""
    if hypotheses:
        hyps_str = " ".join(f"(h{i} : {h})" for i, h in enumerate(hypotheses))
    vars_str = ""
    if variables:
        vars_str = " ".join(variables)

    # Build primary tactic attempt
    primary_tactic = tactics[0] if tactics else "simp"
    fallback_tactics = "\n  · ".join(f"try {t}" for t in tactics[1:3]) if len(tactics) > 1 else ""

    script = f"""import Mathlib

namespace {namespace}

/-- Auto-generated theorem: {theorem_name}
    Statement: {statement}
    Generated by AXIOM MIP — Department B (Formal Mathematics)
-/
theorem {theorem_name.replace(' ', '_').replace('-', '_')} {vars_str} {hyps_str}: {statement} := by
  {primary_tactic}
"""
    if fallback_tactics:
        script = script.rstrip() + f"\n  · {fallback_tactics}\n"

    script += f"\nend {namespace}\n"

    return Lean4Result(
        theorem_name=theorem_name,
        script=script,
        suggested_tactics=tactics,
        fallback_mode=False,
    )


def check_lean4_available() -> bool:
    """Check if the Lean 4 compiler is available."""
    try:
        result = subprocess.run(["lean", "--version"], capture_output=True, timeout=5)
        return result.returncode == 0
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


def compile_lean4(script: str, timeout_seconds: int = 30) -> tuple[bool, str]:
    """
    Compile a Lean 4 script.
    Returns (success, output/error).
    Falls back to AST simulation if lean is not available.
    """
    if not check_lean4_available():
        logger.warning("lean4 compiler not found — running fallback simulation")
        return _simulate_lean4_check(script)

    try:
        import tempfile, os
        with tempfile.NamedTemporaryFile(mode="w", suffix=".lean", delete=False) as f:
            f.write(script)
            tmp_path = f.name

        result = subprocess.run(
            ["lean", tmp_path],
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )
        os.unlink(tmp_path)

        if result.returncode == 0:
            return True, result.stdout
        else:
            return False, result.stderr
    except subprocess.TimeoutExpired:
        return False, "TIMEOUT: Lean 4 compilation exceeded time limit"
    except Exception as exc:
        return False, f"ERROR: {exc}"


def _simulate_lean4_check(script: str) -> tuple[bool, str]:
    """
    Fallback AST simulation when lean4 is not installed.
    Checks for obvious syntax issues.
    """
    issues = []
    if "theorem" not in script:
        issues.append("No 'theorem' declaration found")
    if ":= by" not in script and ":=" not in script:
        issues.append("No proof body found")
    if script.count("import") == 0:
        issues.append("WARNING: No imports (Mathlib likely needed)")

    if issues:
        return False, "SIMULATION ERRORS:\n" + "\n".join(issues)

    logger.warning("Lean 4 not installed. Simulation: script appears structurally valid.")
    return True, "SIMULATION: Script appears structurally valid (lean4 not installed)"
